// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDokD6mEZVJzlD-S1zHsQrPdBmG2E4RZ_c',
    appId: '1:836969897933:web:34648f9d63ec8daafa6e84',
    messagingSenderId: '836969897933',
    projectId: 'demopro-218e8',
    authDomain: 'demopro-218e8.firebaseapp.com',
    storageBucket: 'demopro-218e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUe9xxH2Kqkteja3Z8l4mcOsTIhKU5Zc',
    appId: '1:836969897933:android:e24e97ab4694c950fa6e84',
    messagingSenderId: '836969897933',
    projectId: 'demopro-218e8',
    storageBucket: 'demopro-218e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-fFPvY9Z07TyRiebKbkglMWjMqHaGjIY',
    appId: '1:836969897933:ios:1785e078c6bf02d9fa6e84',
    messagingSenderId: '836969897933',
    projectId: 'demopro-218e8',
    storageBucket: 'demopro-218e8.appspot.com',
    iosBundleId: 'com.example.demopro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-fFPvY9Z07TyRiebKbkglMWjMqHaGjIY',
    appId: '1:836969897933:ios:1785e078c6bf02d9fa6e84',
    messagingSenderId: '836969897933',
    projectId: 'demopro-218e8',
    storageBucket: 'demopro-218e8.appspot.com',
    iosBundleId: 'com.example.demopro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDokD6mEZVJzlD-S1zHsQrPdBmG2E4RZ_c',
    appId: '1:836969897933:web:72b867d881366cd6fa6e84',
    messagingSenderId: '836969897933',
    projectId: 'demopro-218e8',
    authDomain: 'demopro-218e8.firebaseapp.com',
    storageBucket: 'demopro-218e8.appspot.com',
  );
}
